 id |               title               |                                                                                                           description                                                                                                            | rating | duration |    released_date    |                trailer_link                 | genre_name 
----+-----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+----------+---------------------+---------------------------------------------+------------
 18 | Tenet                             | Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real-time.      |    7.8 | 02:30:00 | 2020-09-03 00:00:00 | https://www.youtube.com/watch?v=LdOM0x0XDMo | Sci-Fi
 18 | Tenet                             | Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real-time.      |    7.8 | 02:30:00 | 2020-09-03 00:00:00 | https://www.youtube.com/watch?v=LdOM0x0XDMo | Action
 19 | Spider-Man: Into the Spider-Verse | Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.                                                          |    8.4 | 01:57:00 | 2018-12-14 00:00:00 | https://www.youtube.com/watch?v=tg52up16eq0 | Action
 19 | Spider-Man: Into the Spider-Verse | Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.                                                          |    8.4 | 01:57:00 | 2018-12-14 00:00:00 | https://www.youtube.com/watch?v=tg52up16eq0 | Adventure
 19 | Spider-Man: Into the Spider-Verse | Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.                                                          |    8.4 | 01:57:00 | 2018-12-14 00:00:00 | https://www.youtube.com/watch?v=tg52up16eq0 | Animation
 20 | Knives Out                        | A detective investigates the death of a patriarch of an eccentric, combative family.                                                                                                                                             |    7.9 | 02:10:00 | 2019-11-27 00:00:00 | https://www.youtube.com/watch?v=qGqiHJTsRkQ | Crime
 20 | Knives Out                        | A detective investigates the death of a patriarch of an eccentric, combative family.                                                                                                                                             |    7.9 | 02:10:00 | 2019-11-27 00:00:00 | https://www.youtube.com/watch?v=qGqiHJTsRkQ | Comedy
 20 | Knives Out                        | A detective investigates the death of a patriarch of an eccentric, combative family.                                                                                                                                             |    7.9 | 02:10:00 | 2019-11-27 00:00:00 | https://www.youtube.com/watch?v=qGqiHJTsRkQ | Drama
 21 | Guardians of the Galaxy           | A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.                                                                                                              |      8 | 02:01:00 | 2014-08-01 00:00:00 | https://www.youtube.com/watch?v=d96cjJhvlMA | Action
 21 | Guardians of the Galaxy           | A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.                                                                                                              |      8 | 02:01:00 | 2014-08-01 00:00:00 | https://www.youtube.com/watch?v=d96cjJhvlMA | Comedy
 21 | Guardians of the Galaxy           | A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.                                                                                                              |      8 | 02:01:00 | 2014-08-01 00:00:00 | https://www.youtube.com/watch?v=d96cjJhvlMA | Adventure
 22 | Avengers: Age of Ultron           | When Tony Stark and Bruce Banner try to jump-start a dormant peacekeeping program called Ultron, things go horribly wrong and it's up to Earth's mightiest heroes to stop the villainous Ultron from enacting his terrible plan. |    7.3 | 02:21:00 | 2015-05-01 00:00:00 | https://www.youtube.com/watch?v=tmeOjFno6Do | Sci-Fi
 22 | Avengers: Age of Ultron           | When Tony Stark and Bruce Banner try to jump-start a dormant peacekeeping program called Ultron, things go horribly wrong and it's up to Earth's mightiest heroes to stop the villainous Ultron from enacting his terrible plan. |    7.3 | 02:21:00 | 2015-05-01 00:00:00 | https://www.youtube.com/watch?v=tmeOjFno6Do | Action
 22 | Avengers: Age of Ultron           | When Tony Stark and Bruce Banner try to jump-start a dormant peacekeeping program called Ultron, things go horribly wrong and it's up to Earth's mightiest heroes to stop the villainous Ultron from enacting his terrible plan. |    7.3 | 02:21:00 | 2015-05-01 00:00:00 | https://www.youtube.com/watch?v=tmeOjFno6Do | Adventure
(14 rows)

